# Generated by Django 4.2 on 2025-04-04 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_consultationreport_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
    ]
